### ISSUE TITLE
Add a copy of the MIT license to the repository

### ISSUE THREAD

**Issue by Calinou** [JezSonic/Advanced-Backgound-Loader#1]
The asset submission says the asset's license is MIT. Please add a copy of the MIT license to the repository to confirm this :slightly_smiling_face:

**Comment by JezSonic** [comment]
Ok. Copy of MIT license has been added. Are there any other issues to fix?

**Comment by Calinou** [comment]
Thanks! I approved the asset: https://godotengine.org/asset-library/asset/468
