### ISSUE TITLE
Loading an already loaded scene causes error

### ISSUE THREAD

**Issue by nonunknown** [JezSonic/Advanced-Backgound-Loader#2]
I'm testing here, and I have this flow: language_select->menu->gameplay->menu

everything works well, until I have to go to menu from the gameplay. I got this error:

![image](https://user-images.githubusercontent.com/58845030/106586708-89811480-6527-11eb-9e9c-889ada3fae97.png)

do you have any idea on how to solve that?

PS: I've converted your BackgrounLoader to Csharp, the code is the same, so this is not the problem here!

The C# Version:

```csharp
using Godot;
using System;

namespace Common 
{
    
    public class BackgroundLoader : Node
    {
        public static BackgroundLoader instance = null;
        Resource res;
        public bool canChange = false;
        Thread thread;
        Node newScene;
        string scenePath = "";

        public override void _Ready()
        {
            instance = this;
        }
        private void ThreadLoad(string path) {
           ResourceInteractiveLoader ril = ResourceLoader.LoadInteractive(path);
           int total = ril.GetStageCount();
           res = null;
           while(true) {
               Error err = ril.Poll();
               if (err == Error.FileEof) {
                   res = ril.GetResource();
                    canChange = true;
                    break;
               }
                else if (err != Error.Ok) {
                    GD.Print("ERROR LOADING");
                    break;
                }

           }
        }

        private void ClearStuff() {
            thread = null;
            newScene = null;
            scenePath = "";
            canChange = false;
            res = null;
        }
        private void ThreadDone(PackedScene packedScene) {
            thread.WaitToFinish();
            newScene = packedScene.Instance();
            GetTree().CurrentScene.Free();
            GetTree().CurrentScene = null;
            GetTree().Root.AddChild(newScene);
            GetTree().CurrentScene = newScene;
            ClearStuff();
            
        }

        public void PreloadScene(string path) {
            GD.Print("Calling new Scene");
            scenePath = path;
            canChange = false;
            thread = new Thread();
            thread.Start(this,nameof(ThreadLoad), path);
            Raise();
        }

        public void ChangeSceneToPreloaded() {
            CallDeferred(nameof(ThreadDone), res);
        }


       


    }
}


```

**Comment by JezSonic** [comment]
Dude, you did amazing work converting it to c#
Also about the error, i can fix this, but not today - tommorow. Thank you for reporting this

**Comment by JezSonic** [comment]
I think that, scene after preloading is sthill alocated in memory, so you after preloading should just change scene. There are two ways to fix it:
automatically just change scene if it is alocated in memory
or
unload scene from memory when it was changed to the differrent scene

**Comment by nonunknown** [comment]
> Dude, you did amazing work converting it to c#

Thanks haha, Since I use godot, I use your plugin for all my projects, its really awesome. Fell free to add it to your repo.

> There are two ways to fix it:
automatically just change scene if it is alocated in memory
or
unload scene from memory when it was changed to the differrent scene

Well The second option makes more sense in terms of optimizations, so how I'm supposed to unload it from memory? I'll be so glad to have this solve, probably this is also causing another bug where exported project crashes randomly, so the fast we solve this the better.

best regards...

**Comment by JezSonic** [comment]
For now I'll try to write code to automatically unload this from memory so you won't have to write more code.

I'll add your c# version when I'll get on my pc

**Comment by JezSonic** [comment]
So... i wrote code to clear some variables (i did it online, on GitHub, so idk if this fixes bug properly). Later i will test this on PC

**Comment by nonunknown** [comment]
nice, I can already use it? or there's more todo?, I have to release a demo this week, and this bug is messing things up ;-;

**Comment by JezSonic** [comment]
i don't think there are any errors, but as i said, i didn't checked this code in work. so you can try it and if you can let me know about errors

**Comment by JezSonic** [comment]
like... I'm on pc where i can't install godot
I will be on my PC in.. 2 hours

**Comment by nonunknown** [comment]
just to be clear, this clear_stuff() dont solve any problem, just clear variables, to check the problem of this topic you should try:

having scenes A,B and C

start at A, load B, then C, after loading C load B again. (game should break)

**Comment by JezSonic** [comment]
clear_stuff() seems fixing this bug

**Comment by JezSonic** [comment]
i have tried `start at A, load B, then C, after loading C load B again` this and after clearing stuff theres no error. Give me >hour to upload code

**Comment by nonunknown** [comment]
if this solved the bug, then maybe theres a bug on C#'s Godot.Thread function, I'll try using Default C# Thread

Edit: I think for a strange reason, here the problem seems to be solved, I think the bug was my mistake (I was spawning some nodes under the root node, items,zombies,etccc) after spawning them inside GetTree().CurrentScene seems the bug has gone!

**Comment by JezSonic** [comment]
when youll finish c# fell free to open pull request there :D also as i said i'll update code

**Comment by nonunknown** [comment]
ok I'll do here using default C# thread

**Comment by nonunknown** [comment]
YEAH dude, it solved, I'm using System.Threading, and it has worked!!!

**Comment by JezSonic** [comment]
> YEAH dude, it solved, I'm using System.Threading, and it has worked!!!

Thank you, dude i am using the c# version in my game now

**Comment by JezSonic** [comment]
Also thanks for editing Readme.md

**Comment by JezSonic** [comment]
Now i have requested asset update that includes your c# version.

![image](https://user-images.githubusercontent.com/45912895/106864772-9ab65680-66ca-11eb-8d8e-1852cc3159cc.png)

**Comment by nonunknown** [comment]
Glad to help 👯
